{{ config(materialized="view", schema="ER_DIAG2ID", alias="AFFAIRE") }}

select
    try_to_number(id_affaire) as id_affaire,
    try_to_number(id_syndic_bailleur) as id_syndic_bailleur,
    lpad(cast(code_postal as varchar), 5, '0') as code_postal,
    left(code_postal_livraison, 5) as code_postal_livraison,
    try_to_date(date_creation, 'DD/MM/YYYY HH24:MI:SS') as date_creation,
    try_to_date(date_debut, 'DD/MM/YYYY HH24:MI:SS') as date_debut,
    try_to_date(date_fin, 'DD/MM/YYYY HH24:MI:SS') as date_fin,
    left(fonction_contact_1, 50) as fonction_contact_1,
    left(fonction_contact_2, 50) as fonction_contact_2,
    left(mail_contact_1, 100) as mail_contact_1,
    left(mail_contact_2, 100) as mail_contact_2,
    try_to_number(nb_batiments) as nb_batiments,
    try_to_number(nb_logements) as nb_logements,
    left(nom_contact_1, 50) as nom_contact_1,
    left(nom_contact_2, 50) as nom_contact_2,
    left(numero_affaire, 11) as numero_affaire,
    left(numero_voie, 6) as numero_voie,
    left(numero_voie_livraison, 6) as numero_voie_livraison,
    left(prenom_contact_1, 50) as prenom_contact_1,
    left(prenom_contact_2, 50) as prenom_contact_2,
    left(cast(rapport_recu as varchar), 1) as rapport_recu,
    lpad(cast(telephone_contact_1 as varchar), 10, '0') as telephone_contact_1,
    lpad(cast(telephone_contact_2 as varchar), 10, '0') as telephone_contact_2,
    left(cast(usage_chauffage_coll as varchar), 1) as usage_chauffage_coll,
    left(cast(usage_chauffage_ind as varchar), 1) as usage_chauffage_ind,
    left(cast(usage_cuisson as varchar), 1) as usage_cuisson,
    left(cast(usage_eau_coll as varchar), 1) as usage_eau_coll,
    left(cast(usage_eau_ind as varchar), 1) as usage_eau_ind,
    left(ville, 50) as ville,
    left(ville_livraison, 50) as ville_livraison,
    left(voie, 50) as voie,
    left(voie_livraison, 50) as voie_livraison,
    try_to_number(id_prestataire) as id_prestataire,
    left(code_statut_affaire, 6) as code_statut_affaire,
    left(code_type_affaire, 6) as code_type_affaire,
    try_to_number(taux_ppm) as taux_ppm,
    try_to_date(date_coupure, 'DD/MM/YYYY HH24:MI:SS') as date_coupure,
    try_to_number(cep) as cep

from {{ source("diag2id", "AFFAIRE_TEMP") }}
